import type { ArchiveProject } from './types';

export const MEEDEE_ARCHIVE: ArchiveProject = {
  title: 'meedee',
  year: '2026',
  status: 'Work in progress',
  wipTag: 'WIP',
  subtitle: 'Personal MIDI & Hardware Exploration',
  author: 'Glauber',
  location: 'Los Angeles, CA',
  entries: [
    {
      id: '2026-08-18',
      date: '2026-08-18',
      formattedDate: 'August 18, 2026',
      title: 'Housing & 3D Printing Iterations',
      category: 'Enclosure · CAD',
      text: [
        'It’s taking me a few days to figure out the details of the bottom part of the housing. This is a very slow process. Each iteration takes a lot of time, between CAD and 3D printing. Printing has taken around 1h–1h30, and that’s only when I notice whether something worked or not.',
        'This led me to make custom connectors with more flexible wires as well. It was very difficult to compress the components with the cables I bought previously. I really wanted to stay away from the square shape, but honestly, it’s just easier if I move on with a basic enclosure and learn more things during the process.',
      ],
      specs: [
        { label: 'Print Time', value: '1h 24m / slice' },
        { label: 'Material', value: 'Matte PLA · 0.16mm' },
        { label: 'Tolerance', value: '±0.15mm snap fit' },
        { label: 'Connectors', value: 'Custom JST-SH 1.0mm' },
      ],
      assets: [
        {
          id: 'asset-08-18-1',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/2026-08-18-2_20260818032131.jpg',
          alt: 'Enclosure base CAD alignment and 3D print test',
          width: 2000,
          height: 2000,
          caption: 'Iteration 04 · Bottom shell snap-fit clearance',
        },
        {
          id: 'asset-08-18-2',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/2026-08-18-3_20260818032132.jpg',
          alt: 'Internal component mounting assembly',
          width: 2000,
          height: 2000,
          caption: 'Internal cavity routing with flexible silicone wire',
        },
        {
          id: 'asset-08-18-3',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/2026-08-18-7_20260818032139.jpg',
          alt: 'Flexible wiring connectors',
          width: 2000,
          height: 2000,
          caption: 'Custom micro-connectors for compact chassis depth',
        },
        {
          id: 'asset-08-18-4',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/2026-08-18-6_20260818032137.jpg',
          alt: 'Enclosure top plate mockup',
          width: 2000,
          height: 2000,
          caption: 'Top bezel edge beveling and switch port',
        },
      ],
    },
    {
      id: '2026-08-12',
      date: '2026-08-12',
      formattedDate: 'August 12, 2026',
      title: 'First Board Assembly & Boot',
      category: 'Hardware · Assembly',
      text: [
        'Days after receiving the board and waiting for other things to align, I could finally assemble and test Meedee 1. I’m still flying in my head to think that I have a custom PCB that existed based on a breadboard prototype and very soon will look like a finished product.',
        'There were no errors of any kind when booting the board for the first time. Claude was incredibly helpful in each step and even warned me about JST connectors having switched wires that would damage the board. Had to make sure the LiPo battery wires landed on the right pins.',
      ],
      specs: [
        { label: 'Compute', value: 'Raspberry Pi CM4 Lite' },
        { label: 'Power', value: '3.7V LiPo · TP4056 IC' },
        { label: 'Boot Time', value: '4.2s to MIDI ready' },
        { label: 'Logic Level', value: '3.3V UART / I2C' },
      ],
      assets: [
        {
          id: 'asset-08-12-1',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/img-0177_20260812191037.jpg',
          alt: 'Meedee 1 assembled PCB prototype on desk',
          width: 3024,
          height: 4032,
          caption: 'Meedee Rev 1.0 assembled board boot verification',
        },
        {
          id: 'asset-08-12-2',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/poster_20260812191257.jpg',
          alt: 'OLED screen initial interface test',
          width: 2160,
          height: 3840,
          caption: 'TFT graphical readout: MIDI track buffer 01',
        },
      ],
    },
    {
      id: '2026-08-05',
      date: '2026-08-05',
      formattedDate: 'August 5, 2026',
      title: 'PCB Delivery & CM4 High-Density Connector',
      category: 'Fabrication · Delivery',
      text: [
        'The PCB finally arrived! Amazing quality. I was really concerned about the Raspberry CM4 not fitting in, as it has high-density micro strips that connect with the meedee board. If that failed, nothing would work. But it’s seating perfectly there.',
        'It’s amazing to think that this started as a bet with Claude Code and so far, things seem great. Now, it’s time to test. Fingers crossed!',
      ],
      specs: [
        { label: 'Layers', value: '4-layer FR4 · ENIG Gold' },
        { label: 'Dimensions', value: '55mm × 40mm' },
        { label: 'Connector', value: 'Hirose DF40 100-pin' },
        { label: 'Thickness', value: '1.2mm board profile' },
      ],
      assets: [
        {
          id: 'asset-08-05-1',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/2026-08-04-2_20260805002741.jpg',
          alt: 'Close-up macro of ENIG gold contacts and traces',
          width: 2000,
          height: 2667,
          caption: 'ENIG finish and Hirose DF40 socket mating',
        },
        {
          id: 'asset-08-05-2',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/2026-08-04-4_20260805013249.jpg',
          alt: 'Overhead view of fabricated 4-layer PCB',
          width: 3000,
          height: 3000,
          caption: 'Top copper layer with silkscreen typography',
        },
      ],
    },
    {
      id: '2026-07-15',
      date: '2026-07-15',
      formattedDate: 'July 15, 2026',
      title: 'KiCad Hi-Fi 3D PCB Renders',
      category: 'Design · EDA',
      text: [
        'I didn’t know KiCad could generate hi-fi 3D models of the PCBs. Really cool to be able to see so many details of something no one would ever see. Love this! While I wait, here are some cool cheap renderings of a blown-up PCB.',
      ],
      specs: [
        { label: 'CAD Tool', value: 'KiCad 8.0 + FreeRouting' },
        { label: 'Trace Width', value: '0.15mm signal / 0.4mm pwr' },
        { label: 'Via Size', value: '0.45mm pad / 0.2mm drill' },
        { label: 'Render Engine', value: 'Raytraced ambient occlusion' },
      ],
      assets: [
        {
          id: 'asset-07-15-1',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/render15_20260715074412.jpg',
          alt: 'KiCad 3D render isometric angle',
          width: 2000,
          height: 2000,
          caption: 'Blown-up view of surface-mount passives',
        },
        {
          id: 'asset-07-15-2',
          type: 'image',
          url: 'https://glauber.b-cdn.net/meedee/render20_20260715074412.jpg',
          alt: 'KiCad 3D render orthogonal trace topology',
          width: 2000,
          height: 2000,
          caption: 'Orthogonal routing density through differential pairs',
        },
      ],
    },
  ],
};
